name: Auto Release
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@main
    - name: Create Archive
      run: zip -9 -r -u animation-vs-noname.zip *
    - name: Upload Release
      uses: softprops/action-gh-release@master
      with:
        files: animation-vs-noname.zip
        name: Animation vs. Noname
        tag_name: AvN
